### ISSUE TITLE
[SR Support] number mismatch in Prevalance of anemia

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/sewa-rural#197]
https://reporting.avniproject.org/question/2339-prevalence-of-anemia-new

**Comment by sachsk** [comment]
For total HB recorded and HB not done we are taking value from the baseline only, but in other indicators, we are taking value from the latest encounter and the Hb question in all encounters is non-mandatory. so if the latest encounter has null in HB then that value is not added in the "HB not done" indicator".  because of this issue the number of total HB recorded is not matching with the sum of all indicators.

@utkarshavni  can we mark the HB questions as mandatory in all encounters? if the user doesn't have value then we can auto-populate from the last encounter.

**Comment by sachsk** [comment]
can we mark the HB questions as mandatory in all encounters? if the user doesn't have value then we can auto-populate from the last encounter.
@utkarshavni can you confirm once?

**Comment by pkundu** [comment]
@salilsamanvay please get this closed if done
